### ISSUE TITLE
Calendar still empty with GET 500 error on thread.py

### ISSUE THREAD

**Issue by mdoappway** [BottlecapDave/HomeAssistant-OutlookCalendar#6]
I successfully installed the component on a Home Assistant Core. Integrated with outlook (on a localhost env).
I connected with Outlook and generated both outlook_calendar.yaml and .outlook_calendar.token.

When accessing the Calendar tab in HA I see my calendar list as for those in outlook_calendar.yaml, although the month grid it is never populated and in fact in the browser I see GET network 500 error

app.a9501bd7.js:20473 
GET http://192.168.1.105:8123/api/calendars/calendar.calendario?start=2020-09-26T22:00:00.000Z&end=2020-11-07T23:00:00.000Z

And in the HA logs here what is happening:

Log Details (ERROR)
Logger: aiohttp.server
Source: custom_components/outlook_calendar/calendar.py:175
First occurred: 9:26:34 PM (8 occurrences)
Last logged: 9:28:43 PM

Error handling request
```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/calendar/__init__.py", line 192, in get
    request.app["hass"], start_date, end_date
  File "/home/homeassistant/.homeassistant/custom_components/outlook_calendar/calendar.py", line 120, in async_get_events
    return await self.data.async_get_events(hass, start_date, end_date)
  File "/home/homeassistant/.homeassistant/custom_components/outlook_calendar/calendar.py", line 175, in async_get_events
    items = await hass.async_add_executor_job(self.calendar_service.get_events(**params))
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'list' object is not callable
```

Can you support me here? Don't know how to fix the problem (I'm not a Python expert)

**Comment by BottlecapDave** [comment]
Hello, sorry I didn't get a chance to look at your issue.

This component has been archived in favour of https://github.com/PTST/O365-HomeAssistant. A fork of this component exists at https://github.com/BottlecapDave/O365-HomeAssistant/tree/feature/configurable-scopes which includes support for restricting access to read only to match this component.
